# [Defaults]
# target_file = 480pxTarget.bmp
# target_center = [240,240]
# target_radius = 240
# max_score = 10
# option = haf
# video_source = "http://192.168.1.60/snapshot.jpg"

# target_file: "480pxTarget.bmp"
# calibration_image: "shootinggallery/imgs/480pxTarget.png"
calibration_image: "shootinggallery/imgs/480pxTarget_dark.png"
# target_center: [320,240]
# target_radius: 240
# max_score: 10
# video_source: "http://192.168.1.60/snapshot.jpg"
video_source: 1
resolution: [1024, 768]
video_source_resolution: [640, 480]
auto_target_calibration_white_var_alpha: 1.8
auto_target_calibration_min_area: 15
targets: {
    'paper_target': {
        'impath': "shootinggallery/imgs/480pxTarget.png",
        'center': [512, 384],
        'radius': 384,
        'heading': None,
        'max_score': 10.5,
        'vector': [0, 0],
        'start': [515, 384],
    },
    'projector_target': {
        'impath': "shootinggallery/imgs/480pxTarget_dark.png",
        'center': [512, 384],
        'radius': 384,
        'heading': None,
        'max_score': 10.5,
        'vector': [0, 0],
        'start': [515, 384],
    },
    'paper_target_alpha': {
        'impath': None,
        'center': [320, 240],
        'radius': 240,
        'heading': None,
        'max_score': 10.0,
        'vector': [0, 0],
        'start': [320, 240],
    },
    'fox': {
        'impath': 'shootinggallery/imgs/fox.png',
        'center':[250, 280],
        'radius': 40,
        'heading': 'left',
        'max_score': 10.0,
        'lifetime': 25.0,
        'zoom': 0.3,
        'vector': [-155, 2],
        'vector_var': [30, 2],
        'start_var': [1, 5],
        'start': [1060, 650],


    },
    'picker': {
        'impath': 'shootinggallery/imgs/mushroom_picker.png',
        'center':[250, 320],
        'radius': 210,
        'heading': 'left',
        'max_score': -50.0,
        'vector': [35, 3],
        'vector_var': [4, 2],
        'start_var': [1, 4],
        'lifetime': 35.0,
        'zoom': 0.4,
        'start': [-40, 615]
    },
    'pig': {
        'impath': 'shootinggallery/imgs/pig.png',
        'center':[640, 330],
        'radius': 160,
        'heading': 'left',
        'max_score': 10.0,
        'vector': [65, -1],
        'vector_var': [5, 2],
        'start_var': [1, 4],
        'lifetime': 45.0,
        'zoom': 0.2,
        'start': [-20, 660]

    },
    'deer':{
        'impath': 'shootinggallery/imgs/deer.png',
        'center':[600, 465],
        'radius': 75,
        'heading': 'left',
        'max_score': 10.0,
        'vector': [55, -3],
        'vector_var': [7, 2],
        'start_var': [1, 4],
        'lifetime': 20.0,
        'zoom': 0.3,
        'start': [-20, 680]
    },
}
scenes: {
    0:{
        'background': None,
        'foreground': None,
        'offset': [0, 0],
        'zoom': 1.0,
        'fontsize': 768,
        'free_game': true,
        'game_time': None,
        'targets':[{
            'target_key': 'paper_target',
            'start' : [10, 10],
            'mean_time': None,
        }]
    },
    1:{
        'background': None,
        'foreground': None,
        'offset': [0, 0],
        'zoom': 1.0,
        'fontsize': 270,
        'game_time': 40,
        'targets':[{
            'target_key': 'projector_target',
            'start' : [10, 10],
            'mean_time': None,
        }]
    },
    2:{
        'background': {
            'impath': './shootinggallery/imgs/02.jpg',
            'offset': [0, 0],
            'zoom' : 0.4, 
            # 'invert_intensity': True,
            # 'intensity_multiplier': 0.5,


            },
        'foreground': None,
        'game_time': 40,
        'targets':[{
            'target_key': 'pig',
            'mean_time': 7,
        },{
            'target_key': 'pig',
            'config':{
                'zoom': 0.15,
                'start' : [-30, 610],
                'vector': [25, -4]
            },
            'mean_time': 6,
        },{
            'target_key': 'fox',
            'mean_time': 11,
        },{
            'target_key': 'picker',
            'mean_time': 9,
        },{
            'target_key': 'deer',
            'mean_time': 12,
        },{
            'target_key': 'deer',
            'mean_time': 11,
            'config':{
                'zoom': 0.3,
                'start' : [-40, 610],
                'vector': [65, -3]
            },
        }]
    },
    3:{
        'background': {
            'impath': './shootinggallery/imgs/02_black.jpg',
            'offset': [0, 0],
            'zoom' : 0.4, 
            # 'invert_intensity': True,
            # 'intensity_multiplier': 0.5,


            },
        'foreground': None,
        'game_time': 40,
        'targets':[{
            'target_key': 'pig',
            'mean_time': 7,
        },{
            'target_key': 'pig',
            'config':{
                'zoom': 0.15,
                'start' : [-30, 610],
                'vector': [25, -4]
            },
            'mean_time': 6,
        },{
            'target_key': 'fox',
            'mean_time': 11,
        },{
            'target_key': 'picker',
            'mean_time': 9,
        },{
            'target_key': 'deer',
            'mean_time': 12,
        },{
            'target_key': 'deer',
            'mean_time': 11,
            'config':{
                'zoom': 0.3,
                'start' : [-40, 610],
                'vector': [65, -3]
            },
        }]
    },
}
